# Generated by Django 4.2.7 on 2024-05-11 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('REApp', '0009_feedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='name',
            new_name='Name',
        ),
    ]
